### ISSUE TITLE
Download data - remove empty datasets

### ISSUE THREAD

**Issue by DMEthier** [BirdStudiesCanada/NatureCounts-TO-DO#55]
Download data tab on NC web portal. 

Could we remove datasets from the list that have no data rows associated with them (e.g., GBHE Colony Monitoring BC). Otherwise, the user gets an error when trying to request these data, which causes confusion. Merci!

**Comment by denislepage** [comment]
Good idea. @cjardine-bsc  can likely change the view to exclude collections with 0 records.

**Comment by cjardine-bsc** [comment]
It actually already does that. The problem is that that collection actually has a value in n_records in the collection table: 

collection	collection_name	collection_name_fr	project_id	bmdr_code	akn_level	bmde_version	n_records	n_locations	min_year	max_year
GBHE_BC	Great Blue Heron Colony Monitoring BC	NULL	1054	GBHE_BC	3	BMDE2.00	**998**	300	1932	2016

However it doesn't actually have any records in the bmde_data table (odd). I changed the summary data in the collections table for the time being.
